library(raster)
require(plotrix)
library(classInt)
library(data.table)
library(maptools)
library(rgeos)
library(tidyverse)
library(tigris); options(tigris_use_cache = TRUE)
library(lubridate)
library(sf)
library(rgdal)
#library(con2aqi)
library(nngeo)
