library(tidyverse)
library(dplyr)
library(wesanderson)
library(pdftools)
require(plotrix)
library(scales)
library(forcats)
library(classInt)
library(sp)
library(fst)
library(data.table)
library(maptools)
library(stringr)
library(readxl) #read_excel()
library(writexl) #write_xlsx() without java dependencies
library(rgeos)
library(tigris); options(tigris_use_cache = TRUE)
library(lubridate)
library(sf)
library(colorspace)
library(fixest)
library(feather)
library(future)
library(nngeo)
library(drake)
library(mapview)
library(tools)
library(rNOMADS)
library(FNN)
library(parallel)
library(purrr)
library(Metrics)
library(ggplot2)
library(ggpmisc)
library(ncdf4)
library(future)
library(spdplyr)
library(rnaturalearth)
library(RColorBrewer)
library(s2)
library(anytime)
library(leaflet)
library(lubridate)
library(gridExtra)
library(ggthemes)
library(viridis)
library(ggrepel)
library(cowplot)
library(pbmcapply)
library(pbapply)
library(xtable)
library(ggtext) # element_markdown


