library(tidyverse)
library(raster)
require(plotrix)
library(classInt)
library(data.table)
library(maptools)
library(stringr)
library(readxl) #read_excel()
library(writexl) #write_xlsx() without java dependencies
library(rgeos)
library(tigris); options(tigris_use_cache = TRUE)
library(lubridate)
library(sf)
library(fixest)
library(rgdal)
library(feather)
#library(con2aqi)
library(nngeo)
library(drake)
library(mapview)
library(tools)
library(lubridate)
library(sf)
library(tigris)
library(rNOMADS)
library(FNN)
library(parallel)
library(purrr)
library(Metrics)
library(fixest)
library(ggplot2)
library(ggpmisc)
library(ncdf4)
library(spdplyr)
library(rnaturalearth)
library(RColorBrewer)
library(s2)
library(anytime)
